name: RevampCollectors
main: eu.revamp.collectors.RevampCollectors
version: "1.0"
author: R3XET
depend: [Vault, Factions]
commands:
  revampcollectors:
    description: Give a player a chunk collector.
    aliases: [collector, chunkcollector, chunkcollector]
    permission: revampcollector.give
